services:
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: cd task-q1/server && npm install
    startCommand: cd task-q1/server && node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: |
      cd task-q1/client
      npm install react-scripts
      npm install @testing-library/jest-dom@5.17.0 @testing-library/react@13.4.0 @testing-library/user-event@13.5.0 axios@1.6.7 react@18.2.0 react-dom@18.2.0 web-vitals@2.1.4
      echo '{
        "name": "furniro-client",
        "version": "0.1.0",
        "private": true,
        "scripts": {
          "start": "react-scripts start",
          "build": "react-scripts build",
          "test": "react-scripts test",
          "eject": "react-scripts eject"
        },
        "browserslist": {
          "production": [">0.2%", "not dead", "not op_mini all"],
          "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
        }
      }' > package.json
      npx react-scripts build
    staticPublishPath: task-q1/client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://furniro-backend-1-pt38.onrender.com
