services:
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: chmod +x build-frontend.sh && ./build-frontend.sh
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://furniro-backend-1-pt38.onrender.com
